package com.example.forest.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * CommentsDto.java
 *
 * Data Transfer Object (DTO) used for transferring comment data
 * between the client and server. Represents both comment creation
 * requests and responses when fetching comments for posts.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CommentsDto {

    /** Unique identifier of the comment (auto-generated by the database). */
    private String id;

    /** Identifier of the post to which this comment belongs. */
    private String postId;

    /** The timestamp representing when the comment was created. */
    private Instant createdDate;

    /** A user-friendly string representation of the time since creation (e.g., "2 hours ago"). */
    private String duration;

    /** The actual textual content of the comment (cannot be blank). */
    @NotBlank
    private String text;

    /** The username of the user who wrote the comment. */
    private String userName;
}
