package com.example.forest.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * SubredditDto.java
 *
 * Data Transfer Object (DTO) used for transferring subreddit/community data
 * between the backend and frontend. Represents both creation requests and
 * responses when listing or fetching subreddit details.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class SubredditDto {

    /** Unique identifier for the subreddit (auto-generated by the database). */
    private String id;

    /** The name of the subreddit/community (must be unique and non-empty). */
    @NotBlank(message = "Community name is required")
    private String name;

    /** A short description explaining the purpose or theme of the subreddit. */
    @NotBlank(message = "Description is required")
    private String description;

    /** Total number of posts currently associated with this subreddit. */
    private Integer numberOfPosts;

    /** Human-readable representation of the time since creation (e.g., "2 days ago"). */
    private String duration;

    /** The username of the user who created or moderates this subreddit. */
    private String userName;
}
