package com.example.forest.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * VideoResponse.java
 *
 * Data Transfer Object (DTO) representing the response returned
 * after a video is uploaded or fetched from the database.
 * Contains metadata and the accessible URL for the video.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class VideoResponse {

    /** Unique identifier for the video (auto-generated by MongoDB). */
    private String id;

    /** The title or name of the uploaded video. */
    private String title;

    /** The publicly accessible URL or API endpoint for streaming the video. */
    private String url;
}
