package com.example.forest.document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoPostDocument.java
 *
 * Represents a post entity stored in the MongoDB "posts" collection.
 * Each post belongs to a subreddit, is created by a user, and may
 * contain attached media (photo or video). The post also maintains
 * voting, notification, and timestamp details.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "posts")
public class MongoPostDocument {

    /** Unique identifier for the post (auto-generated by MongoDB). */
    @Id
    private String id;

    /** The title or name of the post. */
    private String postName;

    /** Optional external URL linked to the post. */
    private String url;

    /** Textual description or body of the post. */
    private String description;

    /** The total number of votes (upvotes - downvotes). Defaults to 0. */
    @Builder.Default
    private Integer voteCount = 0;

    /** Reference to the user who created this post. */
    @DBRef
    private MongoUserDocument user;

    /** Timestamp representing when the post was created. */
    private Instant createdDate;

    /** Reference to the subreddit to which this post belongs. */
    @DBRef
    private MongoSubredditDocument subreddit;

    /** Indicates whether post notifications are enabled for the creator. */
    private boolean notificationStatus;

    /** Embedded photo object attached to the post (if any). */
    private Photo photo;

    /** Embedded video object attached to the post (if any). */
    private Video video;
}
