package com.example.forest.document;

import com.example.forest.model.VoteType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * MongoVoteDocument.java
 *
 * Represents a user's voting action (upvote or downvote) on a post.
 * Each document is linked to a specific user and post, storing the type of vote made.
 * Stored in the MongoDB "votes" collection.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "votes")
public class MongoVoteDocument {

    /** Unique identifier for the vote (auto-generated by MongoDB). */
    @Id
    private String id;

    /** The type of vote made by the user (UPVOTE or DOWNVOTE). */
    private VoteType voteType;

    /** Reference to the post that this vote belongs to. */
    @DBRef
    private MongoPostDocument post;

    /** Reference to the user who cast this vote. */
    @DBRef
    private MongoUserDocument user;
}
