package com.example.forest.document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoVerificationTokenDocument.java
 *
 * Represents a verification token used for account activation or email verification.
 * Each token is linked to a user and stored in the MongoDB "verification_tokens" collection.
 * The token ensures that users confirm their email before their account is fully activated.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "verification_tokens")
public class MongoVerificationTokenDocument {

    /** Unique identifier for the verification token (auto-generated by MongoDB). */
    @Id
    private String id;

    /** The actual token string sent to the user's email for verification. */
    private String token;

    /** Reference to the user who owns this verification token. */
    @DBRef
    private MongoUserDocument user;

    /** The timestamp after which this verification token becomes invalid. */
    private Instant expiryDate;
}
