package com.example.forest.document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoCommentDocument.java
 *
 * Represents a comment stored in the MongoDB "comments" collection.
 * Each comment is linked to a post and a user using database references (DBRef).
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "comments")
public class MongoCommentDocument {

    /** Unique identifier for the comment (auto-generated by MongoDB). */
    @Id
    private String id;

    /** The textual content of the comment. */
    private String text;

    /** Reference to the post on which this comment was made. */
    @DBRef
    private MongoPostDocument post;

    /** The timestamp indicating when the comment was created. */
    private Instant createdDate;

    /** Reference to the user who authored this comment. */
    @DBRef
    private MongoUserDocument user;
}
