package com.example.forest.document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.List;

/**
 * MongoSubredditDocument.java
 *
 * Represents a subreddit-like community within the application.
 * Each subreddit can have multiple posts and is created by a user.
 * Stored in the MongoDB "subreddits" collection.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "subreddits")
public class MongoSubredditDocument {

    /** Unique identifier for the subreddit (auto-generated by MongoDB). */
    @Id
    private String id;

    /** The name of the subreddit (e.g., "technology", "travel"). */
    private String name;

    /** A short description that explains the purpose of the subreddit. */
    private String description;

    /** A list of posts associated with this subreddit. */
    @DBRef
    private List<MongoPostDocument> posts;

    /** The timestamp indicating when the subreddit was created. */
    private Instant createdDate;

    /** Reference to the user who created or manages this subreddit. */
    @DBRef
    private MongoUserDocument user;
}
