package com.example.forest.document;

import com.example.forest.model.Role;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.Set;

/**
 * MongoUserDocument.java
 *
 * Represents a user entity stored in the MongoDB "users" collection.
 * Contains authentication details, role-based permissions, account status,
 * and personalization data such as selected interests.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "users")
public class MongoUserDocument {

    /** Unique identifier for the user (auto-generated by MongoDB). */
    @Id
    private String id;

    /** The user's chosen username (used for login and display). */
    private String username;

    /** The user's encrypted password (hashed before storage). */
    private String password;

    /** The user's email address (used for verification and communication). */
    private String email;

    /** Timestamp representing when the user account was created. */
    private Instant created;

    /** Indicates whether the user's account is active and verified. */
    private boolean enabled;

    /** The user's assigned role (e.g., USER, ADMIN). */
    private Role role;

    /** A set of topic names representing the user's selected interests. */
    private Set<String> interests;
}
