package com.example.forest.document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoRefreshTokenDocument.java
 *
 * Represents a refresh token stored in the MongoDB "refresh_tokens" collection.
 * Each token is linked to a user session and used to securely generate new
 * access tokens without requiring the user to log in again.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "refresh_tokens")
public class MongoRefreshTokenDocument {

    /** Unique identifier for the refresh token (auto-generated by MongoDB). */
    @Id
    private String id;

    /** The actual refresh token string issued to the user. */
    private String token;

    /** The exact time when this token expires and becomes invalid. */
    private Instant expiryDate;
}
