package com.example.forest.document;

import org.bson.types.Binary;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Photo.java
 *
 * Represents an image stored in the MongoDB "photos" collection.
 * Each photo contains a title, binary image data, and an auto-generated ID.
 * Used primarily for attaching photos to posts or storing user-uploaded images.
 */
@Document(collection = "photos")
public class Photo {

    /** Unique identifier for the photo (auto-generated by MongoDB). */
    @Id
    private String id;

    /** A descriptive title or caption for the photo. */
    private String title;

    /** The binary content of the image file. */
    private Binary image;

    // Getters and Setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Binary getImage() {
        return image;
    }

    public void setImage(Binary image) {
        this.image = image;
    }
}
