package com.example.forest.document;

import org.bson.types.Binary;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Video.java
 *
 * Represents a video stored in the MongoDB "videos" collection.
 * Each document stores a title and the actual binary video data.
 * Used for attaching videos to posts or storing user-uploaded video content.
 */
@Document(collection = "videos")
public class Video {

    /** Unique identifier for the video (auto-generated by MongoDB). */
    @Id
    private String id;

    /** A descriptive title or name for the video. */
    private String title;

    /** The binary content of the video file. */
    private Binary video;

    // Getters and Setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Binary getVideo() {
        return video;
    }

    public void setVideo(Binary video) {
        this.video = video;
    }
}
